; =====================================================
; Tracker TI0TEC4-7 — T-Beam AXP2101 V1.2
; Taller Integrador — Escuela de Ingeniería en Electrónica
; =====================================================

[platformio]
default_envs = ttgo-t-beam-v1_2

[env]
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep+

[env:esp32]
platform = espressif32 @ 6.7.0
board = ttgo-t-beam
board_build.partitions = huge_app.csv
monitor_filters = esp32_exception_decoder
upload_speed = 921600

[env:ttgo-t-beam-v1_2]
extends = env:esp32
build_flags =
    -D TTGO_T_Beam_V1_2
    -I variants/ttgo-t-beam-v1_2
lib_deps =
    jgromes/RadioLib @ 7.1.0
    mikalhart/TinyGPSPlus @ 1.0.3
    lewisxhe/XPowersLib @ 0.2.4
